spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # auth server
        - id: auth_route
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
        # signup
        - id: admin_signup_route
          uri: http://localhost:8080
          predicates:
            - Path=/admin
            - Method=POST
          filters:
            - RewritePath=/admin, /api/admins
        # admin server
        - id: admin_route
          uri: http://localhost:8080
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /api/admins/$\{segment}
        # user server (changeable)
        - id: user_route
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8084 # changeable
