spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # auth server
        - id: auth_route
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
        # signup
        - id: admin_signup_route
          uri: http://localhost:8080
          predicates:
            - Path=/admin
            - Method=POST
          filters:
            - RewritePath=/admin, /api/admin
        # admin server
        - id: admin_route
          uri: http://localhost:8080
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /api/admin/$\{segment}
        # user server (changeable)
        - id: user_route
          uri: http://localhost:8082
          predicates:
            - Path=/user/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: TRACE

server:
  port: 8084 # changeable
