spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # Admin Authentication API (인증 서버 8083)
        # 예: http://localhost:8084/auth/admin/login -> http://localhost:8083/api/admin/auth/login
        - id: admin_auth_route
          uri: http://localhost:8083
          predicates:
            - Path=/auth/admin/** # 게이트웨이 외부 노출 경로
          filters:
            - RewritePath=/auth/admin/(?<segment>.*), /api/admin/auth/$\{segment} # 인증 서버 내부 경로

        # User Authentication API (인증 서버 8083)
        # 예: http://localhost:8084/auth/user/login -> http://localhost:8083/api/user/auth/login
        - id: user_auth_route
          uri: http://localhost:8083
          predicates:
            - Path=/auth/user/** # 게이트웨이 외부 노출 경로
          filters:
            - RewritePath=/auth/user/(?<segment>.*), /api/user/auth/$\{segment} # 인증 서버 내부 경로

        # Social Login (인증 서버 8083)
        - id: oauth2_auth_route
          uri: http://localhost:8083
          predicates:
            - Path=/oauth2/authorization/** # 게이트웨이 외부 노출 경로 (OAuth2는 경로를 직접 사용할 가능성 높음)

        # Admin Server API (8080) - 회원가입 포함
        # 예: http://localhost:8084/api/admin/signup -> http://localhost:8080/api/admin (POST)
        # 예: http://localhost:8084/api/admin/users -> http://localhost:8080/api/admin/users
        - id: admin_api_route # Admin Server로 가는 모든 API 요청
          uri: http://localhost:8080
          predicates:
            - Path=/api/admin/** # 게이트웨이 외부 노출 경로 (Admin Server와 동일하게 맞춰서 혼동 방지)
          # filters: # /api/admin/** -> /api/admin/** 이므로 RewritePath 불필요

        # User Server API (8082)
        # 예: http://localhost:8084/api/user/mypage -> http://localhost:8082/api/user/mypage
        - id: user_api_route # User Server로 가는 모든 API 요청
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/** # 게이트웨이 외부 노출 경로 (User Server와 동일하게 맞춰서 혼동 방지)
          # filters: # /api/user/** -> /api/user/** 이므로 RewritePath 불필요


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: TRACE

server:
  port: 8084 # changeable